default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development
  username: root


test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
